### ISSUE TITLE
ATOM plugin

### ISSUE THREAD

**Issue by Faianca** [s-ludwig/sdlang-org#1]
This is the first syntax highlighting for ATOM some logic was copied from the sublime one.

https://github.com/Faianca/atom-sdlang

**Comment by s-ludwig** [comment]
BTW, I'm not familiar with how plugins get installed for Atom, do you think it makes more sense to link to this page instead of github: https://atom.io/packages/sdlang?

**Comment by Faianca** [comment]
Yes Sönke that would be perfect.
