### ISSUE TITLE
Citation for "Who uses SDLang"

### ISSUE THREAD

**Issue by Abscissa** [s-ludwig/sdlang-org#3]
We might want to add a little asterisk/footnote citation to "Who uses SDLang?" citing http://sdl.ikayzo.org/display/SDL/Projects+Using+SDL (mirrored at https://web.archive.org/web/20140814033017/http://sdl.ikayzo.org/display/SDL/Projects+Using+SDL and http://semitwist.com/sdl-mirror/Projects+Using+SDL.html) as the source for that information. Just as a "just in case"/"cover our ass" thing.

**Comment by s-ludwig** [comment]
Good point. I'll add one.
